name: fact
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - cpuonly=2.0
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pip:
    - auto_mix_prep==0.2.0
    - click==8.1.7
    - einops==0.7.0
    - gensim==4.3.2
    - ipdb==0.13.13
    - matplotlib==3.8.1
    - more_itertools==10.2.0
    - openai==1.14.2
    - pandas==1.5.3
    - rich==13.7.1
    - sympy==1.12
    - tomlkit==0.12.4
    - tqdm==4.67.1
    - transformer_lens==2.11.0
    - transformers==4.43.2
    - line_profiler==4.2.0
    - python-json-logger==3.2.1
    - pandas==2.1.4